###############################################################################
#                         docker-compose up --build -d                        #
###############################################################################

services:
    postgres:
        container_name: urls-db
        image: postgres:16
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USERNAME}
            POSTGRES_DB: ${POSTGRES_DATABASE}
        ports:
            - '57002:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: unless-stopped

    pgadmin:
        image: dpage/pgadmin4
        ports:
            - "57003:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: admin
        depends_on:
            - postgres

    webserver:
        container_name: urls-server
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - './public:/application/public'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        depends_on:
            - php-fpm
        ports:
            - '57000:80'
        restart: unless-stopped

    php-fpm:
        container_name:  php-fpm
        build:
            context: .
            dockerfile: docker/php-fpm/Dockerfile
        working_dir: /application
        volumes:
            - ./:/application
        depends_on:
            - postgres
        restart: unless-stopped

    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - "5672:5672"    # AMQP
            - "15672:15672"  # Web UI


volumes:
    postgres_data:
